import { chromium, expect } from '@playwright/test';
import fs from 'node:fs';
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
fs.mkdirSync('artifacts',{recursive:true});
try {
await page.goto('http://127.0.0.1:5173/');
await expect(page.locator('.wu-home-template').first()).toBeVisible();
await page.screenshot({path:'artifacts/home-desktop.png'});
await page.locator('.wu-home-template').first().click();
await page.waitForURL('**/editor');
await expect(page.locator('.monaco-editor').first()).toBeVisible({timeout:30000});
await expect(page.locator('.monaco-editor').first()).toContainText('pinMode');
await page.locator('.monaco-editor .view-lines').first().click();
await page.keyboard.press('Control+End');
await page.keyboard.press('Enter');
await page.keyboard.insertText('// Wireup saved edit');
await page.keyboard.press('Enter');
await expect.poll(()=>page.evaluate(()=>window.__velxioStores.useEditorStore.getState().files.find(f=>f.name.endsWith('.ino')).content)).toContain('Wireup saved edit');
await page.getByTitle(/Save project \(Ctrl\+S\)/).click();
await expect(page.locator('.wu-statusbar')).toContainText('Saved locally');
await page.screenshot({path:'artifacts/editor-desktop.png'});
await page.getByTitle('Run (auto-compiles if needed)',{exact:true}).click();
await expect.poll(async()=>page.evaluate(()=>window.__velxioStores?.useSimulatorStore.getState().boards.some(b=>b.running)),{timeout:90000}).toBe(true);
console.log('SIMULATION_RUNNING');
await page.getByTitle('Stop',{exact:true}).click();
await page.getByRole('link',{name:'Prototype',exact:true}).click();
await expect(page.getByRole('heading',{name:'Make the leap to hardware.'})).toBeVisible();
await expect(page.locator('tbody tr').first()).toBeVisible();
await page.getByRole('button',{name:'Wiring',exact:true}).click();
await expect(page.getByText('No wires in this circuit yet.',{exact:false})).toBeVisible();
await page.getByRole('button',{name:'Assembly',exact:true}).click();
await page.locator('.wu-prototype-checklist input').first().check();
const downloadPromise=page.waitForEvent('download');
await page.getByRole('button',{name:/Project backup/}).click();
const download=await downloadPromise;await download.saveAs('artifacts/project.wireup.json');
await page.screenshot({path:'artifacts/prototype-desktop.png'});
await page.reload();
await expect(page.locator('.wu-prototype-summary h2')).toHaveText('Blink LED');
await page.getByRole('link',{name:'Simulate',exact:true}).click();
await expect(page.locator('.monaco-editor').first()).toContainText('Wireup saved edit');
await expect(page.getByRole('button',{name:'Account',exact:true})).toHaveCount(0);
await page.getByRole('link',{name:'Ideate',exact:true}).click();
await expect(page.locator('.wu-home-project').first()).toBeVisible();
await page.getByRole('button',{name:'Duplicate Blink LED',exact:true}).click();
await expect(page.locator('.wu-home-project')).toHaveCount(2);
await page.getByRole('button',{name:'Rename Blink LED',exact:true}).click();
await page.getByLabel('Project name').fill('Bench test');await page.getByRole('button',{name:'Save name'}).click();
await expect(page.getByRole('button',{name:'Rename Bench test',exact:true})).toBeVisible();
await page.locator('input[type=file]').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{}')});
await expect(page.locator('.wu-home-error')).toBeVisible();
await page.getByRole('button',{name:'Dismiss error'}).click();
await page.locator('input[type=file]').setInputFiles('artifacts/project.wireup.json');await page.waitForURL('**/editor');
await page.getByRole('button',{name:'Assistant',exact:true}).click();
await expect(page.locator('.wu-assistant')).toContainText('WIREUP_AI_API_KEY');
await page.getByRole('button',{name:'Close assistant'}).click();
await page.getByRole('link',{name:'Examples',exact:true}).click();await expect(page.locator('body')).toContainText('Examples');
await page.getByRole('link',{name:'Ideate',exact:true}).click();
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/home-mobile.png'});
await page.locator('.wu-home-template').first().click();await page.waitForURL('**/editor');
await page.getByRole('button',{name:'Circuit',exact:false}).first().click();await page.screenshot({path:'artifacts/editor-mobile.png'});
await page.getByRole('link',{name:'Prototype',exact:true}).click();await page.getByRole('button',{name:'Assembly',exact:true}).click();await page.screenshot({path:'artifacts/prototype-mobile.png'});
console.log('PAGE_ERRORS',errors);expect(errors).toEqual([]);console.log('PASS Wireup real-browser workflow');
}finally{await browser.close();}
